name: "Development workflow - nix-shell"
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  tests:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v17
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: Build
      run: nix-shell --run 'meson build && cd build && ninja'
    - name: Run tests
      run: nix-shell --run 'pytest ./tests'
